version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/"
    versioning-strategy: "increase-if-necessary"
    cooldown:
      default-days: 7
    groups:
      cargo-dependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
